---
version: '2.1'

services:
  plex-meta-manager:
    image: meisnate12/plex-meta-manager:latest
    container_name: pmm_daily
    environment:
      TZ: Europe/Amsterdam
      PMM_TIMES: 18:00,19:00,03:00
    volumes:
      - /srv/storage/plex-meta-manager:/config
    restart: unless-stopped
      
  plex-meta-manager-immediate:
      image: meisnate12/plex-meta-manager:latest
      container_name: pmm_now
      environment:
        TZ: Europe/Amsterdam
        PMM_RUN: true
      volumes:
        - /srv/storage/plex-meta-manager:/config