version: "3.4"
services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    environment:
      PUID: 1000
      PGID: 999
      TZ: Europe/Amsterdam
    volumes:
      - /srv/server-files/freshrss/data:/config 
    ports:
      "8066:80" 
    restart: unless-stopped
