version: "3"
services:
  mkdocs:
    container_name: mkdocs
    #image: squidfunk/mkdocs-material
    image: starbase26/mkdocs-with-themes
    ports:
      - "8005:8000"
    volumes:
      - /srv/server-files/mkdocs:/docs
    stdin_open: true
    tty: true
